export const USERS_RECEIVED = 'USERS_RECEIVED';
export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_CLEAR = 'USERS_CLEAR';
export const USERS_ERROR = 'USERS_USERS_ERROR';

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_RECEIVED = 'USER_INFO_RECEIVED';
export const USER_INFO_ERROR = 'USER_INFO_ERROR';

export const NEW_GLOBAL_NOTIFY = 'NEW_GLOBAL_NOTIFY';
export const RESET_GLOBAL_NOTIFY = 'RESET_GLOBAL_NOTIFY';
